controller:
  hero_chassis_controller:
    type: "hero_chassis_controller/HeroChassisController"  # 插件类型（包名/类名）
    joints:
      - left_front_wheel_joint
      - right_front_wheel_joint
      - left_back_wheel_joint
      - right_back_wheel_joint
    pid:
      p_front_left: 1.0
      i_front_left: 0.0
      d_front_left: 0.0
      p_front_right: 1.0
      i_front_right: 0.0
      d_front_right: 0.0
      p_back_left: 1.0
      i_back_left: 0.0
      d_back_left: 0.0
      p_back_right: 1.0
      i_back_right: 0.0
      d_back_right: 0.0
      p: 1.0
      i: 0.1
      d: 0.1

  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50
